---

- hosts: linux
  user: sysadmin
  vars: 
   ansible_host_key_checking: false
  
  tasks:

  - name: Copiar clave publica a los nodos
    ansible.posix.authorized_key:
      user: sysadmin
      state: present
      key: "{{ lookup('file', '/home/sysamin/.ssh/id_rsa.pub') }}"

  - name: desabilitar login de root por ssh
    ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
    notify: Reiniciar servidor ssh

  - name: desabilitar login por password
    ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PasswordAuthentication'
            line: "PasswordAuthentication no"
    notify: Reiniciar servidor ssh

    
  handlers:
  - name: Reiniciar servidor ssh
    ansible.builtin.systemd:
      state: restarted
      name: sshd
