---
- hosts: linux
  user: sysadmin
  become: true

  tasks:

  - name: Update packages in Rocky Linux
    ansible.builtin.yum:
      name: "*"
      state: latest
    when: ansible_os_family = RedHat


  - name: Update packages in Ubuntu Linux
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_os_family = Debian

 
